#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRv2,           sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     Ultrasonic,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLOW 20         //slow FORWARD speed when d-pad is pressed
#define SLOWR -20       //slow REVERSE speed when d-pad is pressed
#define MULTI -0.5     //multiplier for driving motors: increase this to increase robot movement speed
#define ARMMULTI 0.5  //multiplier for arm movement motors: increase this to increase arm movement speed
#define ARMSTALL 18    //arm stall speed

#include "JoystickDriver.c"



 /*///// MOTORS ///////////////

 A: Cube mechanism motor 1
 B: Cube mechanism motor 2
 C: Cube rack motor
 D: Right motor 1
 E: Right motor 2
 F: Main arm motor 1
 G: Main rack
 H: Main arm motor 2
 I: Flag mechanism
 J: Left motor 1
 K: Left motor 2

 /////////////////////////////

 /////// CONTROLS ////////////

Joystick 1:
  left motors: left analog stick
  right motors: right analog stick
  flag: A/Y

Joystick 2:
  Cube Rack: A/Y
  Wheels: B/X
  Arm: right analog stick
  Arm Stall: R2

 ///////////////////////////*/

void left (int speed) //left motors function

{
	motor[motorJ] = speed;
	motor[motorK] = speed;
}


void right (int speed) //right motors function

{
	motor[motorD] = speed;
	motor[motorE] = speed;
}

void arm (int speed) //arm movement function

{
    motor[motorF] = speed;
    motor[motorH] = speed;
}

void grabber (int speed) //grabber wheels function

{
    motor[motorA] = speed;
    motor[motorB] = speed;
}

void analogmove ()

{
  	if(abs(joystick.joy1_y1) > 10) {left(joystick.joy1_y1 * MULTI);}
  	else {left(0);}

  	if(abs(joystick.joy1_y2) > 10){right(joystick.joy1_y2 * MULTI);}
 		else{right(0);}
}

void servohooks (int position1, int position2)

{
	servo[servo1] = position1;
	servo[servo2] = position2;

}

void forward (int speed)
{
	right(speed);
	left(-speed);

}

void backward (int speed)
{
	right(-speed);
	left(speed);

}

void initialization ()
{
	servo(servo1) = 255;
	servo(servo2) = 0;
	servo(servo3) = 128;
	servo(servo4) = 128;
	servo(servo5) = 0;
	PlaySoundFile("Woops.rso");
	wait1Msec(1000);
}
task main()
{

initialization();
waitForStart();

while(SensorValue(Ultrasonic) > 80){forward(30);}

while (SensorValue(Ultrasonic) < 80)

{
	if (SensorValue(IRv2) == 5)
	{
		PlaySound(soundBeepBeep);
		forward(0);
		wait1Msec(300);
		forward(30); //dummy
		wait1Msec(700);
		forward(0);
		wait1Msec(200);
		servoChangeRate(servo5) = 0;
		servo(servo5) = 80;
		wait1Msec(1000);
		servo(servo5) = 0;
		wait1Msec(400);


		while(SensorValue(IRv2) == 5)
		{forward (20);}
		forward(0);

	}
	else
	{forward(15);}
}

		PlaySound(soundDownwardTones);

		forward(15);
		wait1Msec(500);
		forward(0);
		wait1Msec(200);
		left(-20);
		wait1Msec(1600);
		left(0);
		wait1Msec(100);
		forward(15);
		wait1Msec(3200);
		forward(0);
		wait1Msec(100);
		left(20);
		right(20);
		wait1Msec(1300);
		right(0);
		left(0);
		wait1Msec(100);
		backward(100);
		wait1Msec(2200);
		backward(0);
		wait1Msec(100);


}
