#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     IRv2,           sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SLOW 20         //slow FORWARD speed when d-pad is pressed
#define SLOWR -20       //slow REVERSE speed when d-pad is pressed
#define MULTI -0.5     //multiplier for driving motors: increase this to increase robot movement speed
#define ARMMULTI 0.5  //multiplier for arm movement motors: increase this to increase arm movement speed
#define ARMSTALL 18    //arm stall speed

#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"



 /*///// MOTORS ///////////////

 A: Cube mechanism motor 1
 B: Cube mechanism motor 2
 C: Cube rack motor
 D: Right motor 1
 E: Right motor 2
 F: Main arm motor 1
 G: Main rack
 H: Main arm motor 2
 I: Flag mechanism
 J: Left motor 1
 K: Left motor 2

 /////////////////////////////

 /////// CONTROLS ////////////

Joystick 1:
  left motors: left analog stick
  right motors: right analog stick
  flag: A/Y

Joystick 2:
  Cube Rack: A/Y
  Wheels: B/X
  Arm: right analog stick
  Arm Stall: R2

 ///////////////////////////*/

void left (int speed) //left motors function

{
	motor[motorJ] = speed;
	motor[motorK] = speed;
}


void right (int speed) //right motors function

{
	motor[motorD] = speed;
	motor[motorE] = speed;
}

void arm (int speed) //arm movement function

{
    motor[motorF] = speed;
    motor[motorH] = speed;
}

void grabber (int speed) //grabber wheels function

{
    motor[motorA] = speed;
    motor[motorB] = speed;
}

void analogmove ()

{
  	if(abs(joystick.joy1_y1) > 10) {left(joystick.joy1_y1 * MULTI);}
  	else {left(0);}

  	if(abs(joystick.joy1_y2) > 10){right(joystick.joy1_y2 * MULTI);}
 		else{right(0);}
}

void servohooks (int position1, int position2)

{
	servo[servo1] = position1;
	servo[servo2] = position2;

}

void forward (int speed)
{
	right(speed);
	left(speed);

}

void backward (int speed)
{
	right(-speed);
	left(-speed);

}

void flagservo (int position1, int position2)

{
	servo[servo3] = position1;
	servo[servo4] = position2;
}


task main()

{

servohooks(255, 0);
flagservo(102,154);
servo(servo5) = 255;
wait1Msec(500);

while (true)
  {
  	getJoystickSettings(joystick);

  	switch(joystick.joy1_TopHat)
  	{

  	case 0:
  	left(SLOWR);
  	right(SLOWR);
  	break;

  	case 2:
  	left(SLOWR);
  	break;

  	case 4:
  	left(SLOW);
  	right(SLOW);
  	break;

  	case 6:
  	right(SLOWR);
  	break;

  	default:
		analogmove();
		break;
  	}

  if(abs(joystick.joy2_y1) > 10) {arm(joystick.joy2_y1 * ARMMULTI);}
  else if (joy2Btn(7) == 1) {arm(ARMSTALL);}
  else if (joy2Btn(8) == 1) {arm(ARMSTALL);}
  else if (joy2Btn(5) == 1) {arm(-100);}
  else{arm(0);}

  if (joy2Btn(3) == 1) {grabber(100);}
	else if (joy2Btn(2) == 1) {grabber(-100);}
	else {grabber (0);}

	if (joy2Btn(4) == 1) {motor[motorC] = 100;}
	else if (joy2Btn(1) == 1) {motor[motorC] = -100;}
	else {motor[motorC] = 0;}

	if (joystick.joy2_TopHat == 0) {motor[motorG] = 100;}
  else if (joystick.joy2_TopHat == 4) {motor[motorG] = -100;}
  else {motor[motorG] = 0;}

  if (joy1Btn(4) == 1) {motor[motorI] = 100;}
	else if (joy1Btn(2) == 1) {motor[motorI] = -100;}
	else {motor[motorI] = 0;}

	if (joy1Btn(8) == 1) {servohooks(50, 200);}
	else if (joy1Btn(7) == 1) {servohooks(255, 0);}

	if (joy2Btn(9) == 1) {flagservo(229,27);}
	else if (joy2Btn(10) == 1) {flagservo(102,154);}


	// servo 1: 255 normal 50
	// servo 2: 0 normal 200

}
	}
