#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     lightsensor,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



/* Joystick 1 - Ground Control Movement.
Left Axis - Left Motor F, H
Right Axis - Right Motor G, I
*/

/* JoyStick 2 - Arm Control Movement
Left Axis -
Right Axis - Arm up-down movement
Button 1 - Rack Push / Block Drop
Button 4 - Rack Pull / Block Grab
Button 5 - Block Grab
Button 6 - Block Release
*/


task main()
{



	while (true)
	{
		getJoystickSettings(joystick);

		//Downward Press Left Axis - Joystick 1
		if (abs(joystick.joy1_y1) > 10 && abs(joystick.joy1_y2) < 10 && joystick.joy1_TopHat == -1)
		{
			motor[motorF] = joystick.joy1_y1*-0.45;
			motor(motorG) = joystick.joy1_y1*-0.45;
		}


		// Downward Press Right Axis - Joystick 1
		else if (abs(joystick.joy1_y2) > 10 && abs(joystick.joy1_y1) < 10 && joystick.joy1_TopHat == -1)

		{
			motor[motorH] = joystick.joy1_y2*-0.45;	//Assign power
			motor[motorI] = joystick.joy1_y2*-0.45;
		}

		else if (abs(joystick.joy1_y2) > 10 && abs(joystick.joy1_y1) > 10 && joystick.joy1_TopHat == -1)
		{
			motor[motorF] = joystick.joy1_y1*-0.45;
			motor(motorG) = joystick.joy1_y1*-0.45;
			motor[motorH] = joystick.joy1_y2*-0.45;	//Assign power
			motor[motorI] = joystick.joy1_y2*-0.45;
		}
		else if (abs(joystick.joy1_y2) < 10 && abs(joystick.joy1_y1) < 10 && joystick.joy1_TopHat == 0)
		{
			motor(motorF) = -10;
			motor(motorG) = -10;
			motor(motorH) = -10;
			motor(motorI) = -10;
		}
		else if (abs(joystick.joy1_y2) < 10 && abs(joystick.joy1_y1) < 10 && joystick.joy1_TopHat == 4)
		{
			motor(motorF) = 10;
			motor(motorG) = 10;
			motor(motorH) = 10;
			motor(motorI) = 10;
		}

		else
		{
			motor(motorF) = 0;
			motor(motorG) = 0;
			motor(motorH) = 0;
			motor(motorI) = 0;
		}


		// Dwonward Press Right Axis - Joystick 2
		if ((joystick.joy2_y1) < -10 && joy2Btn(11) == 0 && joy1Btn(6) == 0)

		{
			motor[motorD] = abs(joystick.joy2_y1)*-0.1; //arm down
			motor[motorJ] = abs(joystick.joy2_y1)*-0.1; //arm dwon
		}

		// Upward Press Right Axis - Joystick 2
		else if ((joystick.joy2_y1) > 10 && joy2Btn(11) == 0 && joy1Btn(6) == 0)

		{
			motor[motorD] = joystick.joy2_y1*0.3;	// arm up
			motor[motorJ] = joystick.joy2_y1*0.3; // arm up
		}


		else if (joy2Btn(11) == 1 && (abs(joystick.joy2_y1) > 10 || abs(joystick.joy2_y1) < 10 ) && joy1Btn(6) == 0)
		{
			motor(motorD) = 10; // Arm Stoll
			motor(motorJ) = 10; // Arm Stoll
		}

		else if (joy1Btn(6) == 1 && (abs(joystick.joy2_y1) > 10 || abs(joystick.joy2_y1) < 10 ) && joy2Btn(11) == 0)
		{
			motor(motorD) = 10; // Arm Stoll
			motor(motorJ) = 10; // Arm Stoll
		}

		else
		{
			motor[motorD] = 0;
			motor[motorJ] = 0;
		}

		// Button 6 - Joystick 2 - Grab Block - inward movement
		if (joy2Btn(3)==1)
		{
			motor(motorA) = 100;
			motor(motorB) = 100;
		}



		// Button 5 - Joystick 2 - Release Block - outward movement
		else if(joy2Btn(2) == 1)
		{
			motor(motorA) = -100;
			motor(motorB) = -100;
		}


		else  // stop
		{
			motor(motorA) = 0;
			motor(motorB) = 0;
		}

		if (joy2Btn(4) == 1)
		{
			motor(motorC) = 100;
		}

		else if (joy2Btn(1) == 1)
		{
			motor(motorC) = -100;
		}

		else
		{
			motor(motorC) = 0;
		}

		// Rack Push
		if (joystick.joy2_TopHat == 0)

		{
			motor(motorK) = 100;
		}


		// Rack Pull

		else if (joystick.joy2_TopHat == 4)
		{
			motor(motorK) = -100;
		}

		else
		{
			motor(motorK) = 0;
		}

		// Flag Clockwise
		if (joy1Btn(2) == 1)
		{
			motor(motorE) = 100;
		}


		// Flag Anti-clcokwise
		else if (joy1Btn(4)==1)
		{
			motor(motorE) = -100;
		}

		else
		{
			motor(motorE) = 0;
		}











	}

}
