#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touch2,         sensorTouch)
#pragma config(Sensor, S3,     touch3,         sensorTouch)
#pragma config(Sensor, S4,     touch4,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
getJoystickSettings(joystick);

	motor[motorA] = 50;
	motor[motorB] = 50;

	if (SensorValue[touch2] == 1 && SensorValue[touch4] == 1)
	{
		motor[motorF] = 50;
	}

	else if (SensorValue[touch2] == 1 && SensorValue[touch4] == 0)
	{
			motor[motorF] = -50;
	}

	else
	{
		motor[motorF] = 0;
	}

	if (SensorValue[touch3] == 1 && SensorValue[touch4] == 1)
	{
		motor[motorG] = 50;
	}

	else if (SensorValue[touch3] == 1 && SensorValue[touch4] == 0)
	{
			motor[motorG] = -50;
	}

	else
	{
		motor[motorG] = 0;
	}

	if (joy1Btn(1) == 1  && joy1btn(5) == 1 && joy1btn(2) == 0)
	{
		motor[motorE] = 20;
	}

	else if (joy1Btn(1) == 0 && joy1btn(5) == 1 && joy1btn(2) == 1 )
	{
		motor[motorE] = -20;
	}

	else if (joy1Btn(1) == 0 && joy1btn(5) == 0 && joy1btn(2) == 1 )
	{
		motor[motorE] = -60;
	}

	else if (joy1Btn(1) == 1 && joy1btn(5) == 0 && joy1btn(6) == 0 )
	{
		motor[motorE] = 60;
	}
	else
	{
		motor[motorE] = 0;
	}

	if (joy1Btn(3) == 1  && joy1btn(5) == 1 && joy1btn(4) == 0)
	{
		motor[motorD] = 20;
	}

	else if (joy1Btn(3) == 0 && joy1btn(5) == 1 && joy1btn(4) == 1 )
	{
		motor[motorD] = -20;
	}

	else if (joy1Btn(3) == 0 && joy1btn(5) == 0 && joy1btn(4) == 1 )
	{
		motor[motorD] = -60;
	}

	else if (joy1Btn(3) == 1 && joy1btn(5) == 0 && joy1btn(4) == 0 )
	{
		motor[motorD] = 60;
	}
	else
	{
		motor[motorD] = 0;
	}



























}
}
