//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/* Joystick 1 - Ground Control Movement.
Left Axis - Left Motor F, H
Right Axis - Right Motor G, I
*/

/* JoyStick 2 - Arm Control Movement
Left Axis -
Right Axis - Arm up-down movement
Button 1 - Rack Push / Block Drop
Button 4 - Rack Pull / Block Grab
Button 5 - Block Grab
Button 6 - Block Release
*/

task main()
{
	while (true)
	{
		getJoystickSettings(joystick);

		//Downward Press Left Axis - Joystick 1
		if (abs(joystick.joy1_y1) > 10)
		{
			motor[motorB] = joystick.joy1_y1*-0.3;

		}


		else	//stop
		{
			motor[motorB] = 0;

		}


		// Downward Press Right Axis - Joystick 1
		if (abs(joystick.joy1_y2) > 10)
		{
			motor[motorC] = joystick.joy1_y2*-0.3;	//Assign power
		}


		else	// stop
		{
			motor[motorC] = 0;
		}







	}

}
