#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#include "JoystickDriver.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
	motor[motorA] = 100;
	motor[motorB] = -100;
getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1)>20)
		{
    motor[motorG] = ((joystick.joy1_y1)*1);
		}

		else
		{
			motor[motorG] = 0;
		}

		if(abs(joystick.joy1_y2)>20)
		{
    motor[motorF] = ((joystick.joy1_y2*1));
		}

		else
		{
			motor[motorF] = 0;
		}

	if (joy1Btn(1) == 1)
	{
		motor[motorE] = 20;
	}

	else if (joy1Btn(2) == 1)
	{
		motor[motorE] = -20;
	}

	else if (joy1Btn(6) == 1)
	{
		motor[motorE] = 70;
	}

	else if (joystick.joy1_x2 < -100)
	{
		motor[motorE] = -70;
	}

	else
	{
		motor[motorE] = 0;
	}

	if (joy1Btn(3) == 1)
	{
		motor[motorD] = 20;
	}

	else if (joy1Btn(4) == 1)
	{
		motor[motorD] = -20;
	}

	else if (joy1Btn(5) == 1)
	{
		motor[motorD] = 70;
	}

	else if (joystick.joy1_x2 > 100)
	{
		motor[motorD] = -70;
	}

	else
	{
		motor[motorD] = 0;
	}




}
}
